/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import javax.swing.JButton;
import javax.swing.JMenuItem;






/**
 *
 * @author JoséAlberto
 */
public class GUI extends javax.swing.JFrame {

    /**
     * Creates new form GUI
     */
    String[] line;
    public GUI() {
        initComponents();
        this.setExtendedState(MAXIMIZED_BOTH);
        TextLineNumber numLine = new TextLineNumber(textEditor);
        textScrollPanel.setRowHeaderView(numLine);
        
        FixedColumnExample ejem = new FixedColumnExample();
        
        outputScrollPanel.setViewportView(ejem.table);
        //checkScrollPanel.setViewportView(ejem.fixedTable);
        
        TreeSample tre = new TreeSample();
        treeScrollPanel.setViewportView(tre.tree);
        
        checkScrollPanel.setViewportView(textCheck);
    }
    


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainPanel = new javax.swing.JPanel();
        treeScrollPanel = new javax.swing.JScrollPane();
        outputTab = new javax.swing.JTabbedPane();
        outputScrollPanel = new javax.swing.JScrollPane();
        checkScrollPanel = new javax.swing.JScrollPane();
        textCheck = new javax.swing.JTextPane();
        textScrollPanel = new javax.swing.JScrollPane();
        textEditor = new javax.swing.JTextPane();
        RUN = new javax.swing.JButton();
        menuBar = new javax.swing.JMenuBar();
        File = new javax.swing.JMenu();
        Edit = new javax.swing.JMenu();
        Run = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        mainPanel.setPreferredSize(new java.awt.Dimension(1000, 900));

        outputTab.addTab("Output", outputScrollPanel);

        checkScrollPanel.setViewportView(textCheck);

        outputTab.addTab("Check", checkScrollPanel);

        textScrollPanel.setViewportView(textEditor);

        RUN.setIcon(new javax.swing.ImageIcon("C:\\Users\\JoséAlberto\\Desktop\\Escritorio\\II semestre 2015\\Bases 2015\\icon.png")); // NOI18N
        RUN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RUNActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout mainPanelLayout = new javax.swing.GroupLayout(mainPanel);
        mainPanel.setLayout(mainPanelLayout);
        mainPanelLayout.setHorizontalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainPanelLayout.createSequentialGroup()
                .addComponent(treeScrollPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(outputTab)
                    .addComponent(textScrollPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
                    .addGroup(mainPanelLayout.createSequentialGroup()
                        .addComponent(RUN, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        mainPanelLayout.setVerticalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainPanelLayout.createSequentialGroup()
                .addComponent(RUN)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(textScrollPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 291, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(outputTab, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addComponent(treeScrollPanel)
        );

        File.setText("File");
        menuBar.add(File);

        Edit.setText("Edit");

        Run.setText("Run");
        Run.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RunActionPerformed(evt);
            }
        });
        Edit.add(Run);

        menuBar.add(Edit);

        setJMenuBar(menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 600, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 489, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void RunActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RunActionPerformed
        // TODO add your handling code here:
//        String temp="";
//        line = textEditor.getText().split("\\n");
//        int count = 0;
//        LexicalAnalysis lex = new LexicalAnalysis();
//        Parser par = new Parser();
//        System.out.println("Linea nueva");
//        temp +="Manejo de errores\n";
//        String allEntry = "";
//        while (count <line.length){
//            allEntry += " " + line[count];
//            count++;
//        }
//        int count2 = 0;
//        while (count2<lex.tokenize(allEntry).size()){
//            ArrayList<String> inst =  lex.tokenize(allEntry).get(count2);
//            if (par.parse(lex.tokenize(allEntry).get(count2))){
//                System.out.println("True");
//            }else{
//                int linea = count+1;
//                System.out.println("Error in line: " + linea);
//                temp+="Error in line: " + linea+"\n";
//            }
//        }
//        
//            
//        
//        System.out.println(temp);
//        textCheck.setText(temp);
        
    }//GEN-LAST:event_RunActionPerformed

    private void RUNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RUNActionPerformed
        // TODO add your handling code here:
                String temp="";
        line = textEditor.getText().split("\\n");
        int count = 0;
       LexicalAnalysis lex = new LexicalAnalysis();
        Parser par = new Parser();
        System.out.println("Linea nueva");
        temp +="Manejo de errores\n";
        
        while (count <line.length){
           // LexicalAnalysis lex = new LexicalAnalysis();
            if (par.parse(lex.tokenize(line[count]))){
                System.out.println("True");
            }else{
                int linea = count+1;
               System.out.println("Error in line: " + linea);
                temp+="Error in line: " + linea+"\n";
         }
        count++;}
        textCheck.setText(temp);
    }//GEN-LAST:event_RUNActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu Edit;
    private javax.swing.JMenu File;
    private javax.swing.JButton RUN;
    private javax.swing.JMenuItem Run;
    private javax.swing.JScrollPane checkScrollPanel;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JScrollPane outputScrollPanel;
    private javax.swing.JTabbedPane outputTab;
    private javax.swing.JTextPane textCheck;
    private javax.swing.JTextPane textEditor;
    private javax.swing.JScrollPane textScrollPanel;
    private javax.swing.JScrollPane treeScrollPanel;
    // End of variables declaration//GEN-END:variables

    /**
     * 
     * @return 
     */
    public JButton getRUN() {
        return RUN;
    }

    /**
     * 
     * @param RUN 
     */
    public void setRUN(JButton RUN) {
        this.RUN = RUN;
    }

    /**
     * 
     * @return 
     */
    public JMenuItem getRun() {
        return Run;
    }

    /**
     * 
     * @param Run 
     */
    public void setRun(JMenuItem Run) {
        this.Run = Run;
    }
}
